### ISSUE TITLE
bigger size model

### ISSUE THREAD

**Issue by zlm-ai** [Time-MoE/Time-MoE#11]
Very effective work! Do you have a plan or are you currently continuing to increase the model size? Can you explain the reasons for continuing or not continuing to expand it?

**Comment by zlm-ai** [comment]
By the way, how much time did it take to train your 2.4B model?

**Comment by Maple728** [comment]
Thank you for your interest in our work! We plan to further increase the model size, as the scaling law has proven to be applicable to time-series models in both our experiments and other studies.

Training the TimeMoE-1B model with 128 A100 GPUs took nearly two weeks, including instances of restarting the training.

If you have any other questions, please feel free to contact us!

**Comment by zlm-ai** [comment]
Thank you very much for your reply. Looking forward to seeing your new achievements soon.
