### ISSUE TITLE
Error in evaluating Time-MOE with datasets with many features 

### ISSUE THREAD

**Issue by ChathurangiShyalika** [Time-MoE/Time-MoE#12]
Hello, I evaluated Time-MOE with a dataset that has 2 features and it worked fine. But, when I evaluated back with a dataset that has 20+ features, I'm getting below error. Any idea on how to resolve it?
Thank you

  File ".../Time_MOE/Time-MoE/run_eval.py", line 220, in <module>
    evaluate(args)
  File "../Time_MOE/Time-MoE/run_eval.py", line 141, in evaluate
    preds, labels = model.predict(batch)
                    ^^^^^^^^^^^^^^^^^^^^
  File "../Time_MOE/Time-MoE/run_eval.py", line 72, in predict
    outputs = model.generate(
              ^^^^^^^^^^^^^^^
  File "../.local/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "../.local/lib/python3.11/site-packages/transformers/generation/utils.py", line 1996, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "../.local/lib/python3.11/site-packages/transformers/generation/utils.py", line 2971, in _sample
    model_kwargs = self._update_model_kwargs_for_generation(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "../.cache/huggingface/modules/transformers_modules/Maple728/TimeMoE-50M/446753ee48ff3726d0606a81d0092d54acee995e/ts_generation_mixin.py", line 209, in _update_model_kwargs_for_generation
    model_kwargs["past_key_values"] = self._extract_past_from_model_output(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: GenerationMixin._extract_past_from_model_output() got an unexpected keyword argument 'standardize_cache_format'

**Comment by Maple728** [comment]
I apologize for my delayed response; I missed the email notification.

The `run_eval.py` file utilizes the [BenchmarkEvalDataset](https://github.com/Time-MoE/Time-MoE/blob/main/time_moe/datasets/benchmark_dataset.py#L10) for evaluation, which is designed for a specific CSV format:

```
date,HUFL,HULL,MUFL,MULL,LUFL,LULL,OT
2016/7/1 00:00,5.827000141,2.009000063,1.598999977,0.462000012,4.203000069,1.340000033,30.53100014
2016/7/1 01:00,5.69299984,2.075999975,1.491999984,0.425999999,4.142000198,1.371000051,27.78700066
``` 

The first line lists the columns, with the first column required to be `date` and the remaining columns representing individual time-series.

You might try setting the first column name of `FF_Analog_Encoded_Anomaly_Types.csv` to `date` and using the remaining columns as the features you wish to evaluate.

I hope this resolves your issue.

**Comment by ChathurangiShyalika** [comment]
Hello,
I resolved this issue by upgrading the transformers version to _transformers==4.40.2_.

Thanks for your suggestion.
