### ISSUE TITLE
A problem when spliting the dataset

### ISSUE THREAD

**Issue by 7dy15** [Time-MoE/Time-MoE#16]
Hello,Appreciation on the work!But when I try to do some experiments with the Etth1 dataset as the Readme suggests,the process of spliting dataset is always zero.How can I deal with this problem?
![屏幕截图 2024-11-04 172859](https://github.com/user-attachments/assets/583dcbfb-7675-4a17-86e3-6638284b86c7)

**Comment by ChathurangiShyalika** [comment]
Hi, I experienced similar when working with a large dataset with many variables. Using GPU resources helped me overcome it. May be it will be helpful for you.

**Comment by Maple728** [comment]
Thank you for your interest in our work.

It appears that the prediction speed is quite slow. On an Nvidia A100, evaluating the ETTh1 dataset takes approximately 1 to 2 minutes. However, on my Apple M1 Pro, it takes up to 8 hours, with a single batch taking roughly 48 seconds.

The TimeMoE-Base and TimeMoE-Large models can function as forecasters on CPUs with limited memory and accpetable processing time, but using them for extensive evaluations on a CPU is not recommended.

As @ChathurangiShyalika mentioned, utilizing a GPU may be beneficial for you.

Please feel free to reach out if you have any other questions.

**Comment by 7dy15** [comment]
Sincere thanking for both of your advice,my work return to normal now!An additional question: how can I visualize the result eg:the predictions, is there any tool provided?
