### ISSUE TITLE
Fine-Tuning

### ISSUE THREAD

**Issue by AlexCohenDambros** [Time-MoE/Time-MoE#21]
Hello, first of all, I want to congratulate you on the great work with Time-Moe. I achieved surprising results with zero-shot alone. Now, I am trying to perform fine-tuning with my time series. I followed the instructions in the README and adjusted my data to the jsonl format, like this:

{"sequence": [31059.872, 22527.896, 23241.738, 33170.351, 23838.015, ....]} 
{"sequence": [22430.463, 16776.191, 17012.155, 23411.862, 19375.651, ....]} 

Then I ran the command:

python main.py -d <data_path>

The execution was successful, but I am unsure how to use the model after performing fine-tuning with my data. Thank you in advance.

**Comment by Maple728** [comment]
Apologies for the delayed response.

To load your fine-tuned model and perform forecasting, please use the following command, as outlined in the TimeMoE-50M usage section of the readme.md:

```python
from time_moe.models.modeling_time_moe import TimeMoeForPrediction

model = TimeMoeForPrediction.from_pretrained(
    {path_to_your_fine_tuned_model},
    device_map="cpu",  # Use "cpu" for CPU inference, and "cuda" for GPU inference.
    trust_remote_code=True,
)
```

Alternatively, you can place all files from this [folder](https://github.com/Time-MoE/Time-MoE/tree/main/time_moe/models) in the directory of your fine-tuned model, then follow the instructions in the readme.md to perform forecasting.

If you have any questions, please feel free to contact us.
