### ISSUE TITLE
Making Forecasts errors 

### ISSUE THREAD

**Issue by rkl6666** [Time-MoE/Time-MoE#27]
Thanks for your great works! But I have some problems with the **Making Forecasts** code when I **input below:**

import torch
from transformers import AutoModelForCausalLM

context_length = 12
seqs = torch.randn(2, context_length)  # tensor shape is [batch_size, context_length]
print(seqs.size())

model = AutoModelForCausalLM.from_pretrained(
    'Maple728/TimeMoE-50M',
    device_map="cpu",  # use "cpu" for CPU inference, and "cuda" for GPU inference.
    trust_remote_code=True,
)
prediction_length = 6
output = model.generate(normed_seqs, max_new_tokens=prediction_length)  # shape is [batch_size, 12 + 6]
normed_predictions = output[:, -prediction_length:]  # shape is [batch_size, 6]

**The result show that:**
Traceback (most recent call last):
  File "E:\pycharm project\pythonProject\Time-moe.py", line 25, in <module>
    output = model.generate(normed_seqs, max_new_tokens=prediction_length)  # shape is [batch_size, 12 + 6]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Users\PC\anaconda3\Lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "E:\Users\PC\anaconda3\Lib\site-packages\transformers\generation\utils.py", line 1758, in generate
    result = self._sample(
             ^^^^^^^^^^^^^
  File "E:\Users\PC\anaconda3\Lib\site-packages\transformers\generation\utils.py", line 2446, in _sample
    input_ids = torch.cat([input_ids, next_tokens[:, None]], dim=-1)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Tensors must have same number of dimensions: got 3 and 2

**Comment by Maple728** [comment]
Thank you for your interest in our work!

Please ensure that you are using version `4.40.1` of the `transformers` library, and that the shape of `normed_seqs` is `[batch_size, seq_length]`.

Please note that the shape of `normed_seqs` will be modified after the `generate` function for efficiency reasons, so it should not be used following the execution of `generate`.

Please feel free to contact us, if you have any questions.

**Comment by rkl6666** [comment]
Thank you, the issue has been resolved by using version 4.40.1 of the transformers library.
