### ISSUE TITLE
How to do model fine tuning?

### ISSUE THREAD

**Issue by iganggang** [Time-MoE/Time-MoE#3]
Cool project! Enjoy the paper. Will instructions on fine-tuning be released?

Thanks for your time

**Comment by Maple728** [comment]
Thank you for your interest in our work. We're currently in the process of refining the fine-tuning code and plan to release it either this month or next.

**Comment by Maple728** [comment]
The fine-tuning code is now available! You can find the tutorial in the `README.md`. I hope you find it helpful.

If you have any further questions, please don't hesitate to contact us.
