### ISSUE TITLE
High IO Overhead and Low GPU Utilization During Pretraining on Time-300B Dataset

### ISSUE THREAD

**Issue by GritLs** [Time-MoE/Time-MoE#33]
Hi, 

Thank you for sharing the dataset and codebase! I’m currently using the Time-300B dataset and your code to pretrain a Time-MOE model. However, I’ve noticed significant IO overhead during data loading, which results in very low GPU utilization.

In your paper, you mentioned training with 128 A100 GPUs, which makes me curious about how you organized the dataset loading to achieve such efficiency. Could you share any insights or best practices on optimizing data loading for large-scale pretraining?

Thanks again for your work and support!

Best regards

**Comment by Maple728** [comment]
Thank you for your interest in our work!

The dataset (BinaryDataset) for Time-300B in this repository, used in training Time-MoE, dynamically reads sequences from disk, which can result in significant disk I/O demands. To address this, we've implemented optimizations to reduce the load.

Could you please provide details about your hardware environment, such as whether you're using an SSD or HDD and what type of GPU you have? In our Time-MoE training, we evaluated the data loader's efficiency on NVIDIA A800 and H800 GPUs with SSDs, and we didn't encounter any I/O bottlenecks, even with the TimeMoE-50M model.

I recently tested the GPU utilization when training TimeMoE-50M on an H800 GPU with SSD. The command used was:

```bash
python torch_dist_run.py main.py -m Maple728/TimeMoE-50M -d Time-300B --micro_batch_size 32 --global_batch_size 1024 --dataloader_num_workers 8
```
Below is the GPU utilization graph:

<img width="410" alt="image" src="https://github.com/user-attachments/assets/e85c328a-c5fe-45ed-895a-1d37b574e918" />

Additionally, I compared the training speed between using the BinaryDataset (which reads data dynamically from disk) and the GeneralDataset (which reads data from memory). The results are as follows:

| Data Loader Strategy | Training Speed (s/iter) |
|----------------------|-------------------------|
| BinaryDataset        | 1.31                    |
| GeneralDataset       | 1.30                    |

**BinaryDataset Results:**
<img width="2194" alt="image" src="https://github.com/user-attachments/assets/6780db55-fa07-4137-8863-ba7895cbf816" />

**GeneralDataset Results:**
<img width="2201" alt="image" src="https://github.com/user-attachments/assets/a9c54570-8329-49fa-b978-23bf68bb8480" />

As shown, the training speed is comparable even for TimeMoE-50M.

Here are some tips that may help resolve your issue:

1. Use `torch_dist_run.py` for model training if you have multiple GPUs.
2. Adjust the micro_batch_size until the GPU memory is fully utilized.
3. Increase the `dataloader_num_workers` if necessary, although the default of 4 workers is typically sufficient.

We hope this helps you in optimizing your training process. If you have further questions, please don't hesitate to ask!

**Comment by GritLs** [comment]
Thank you for the detailed information and optimization tips!

I recently moved the dataset to an SSD and retested the training. The IO bottleneck is indeed resolved, and the training process is now much smoother with significantly improved GPU utilization.

Once again, thank you for your support and guidance!
