### ISSUE TITLE
Have you considered multivariate time series forecasting?

### ISSUE THREAD

**Issue by ketusrai** [Time-MoE/Time-MoE#9]
Time series data can be affected by many external factors. For example, in stock prediction, major events can have an impact, or in sales forecasting, factors like price and promotions can cause significant fluctuations in the predicted values. Have you considered incorporating some external factors into the model training process?

**Comment by Maple728** [comment]
Thank you for your interest in our work! At present, Time-MoE only supports univariate time-series forecasting and cannot handle dynamic features. For multivariate time series, we suggest breaking them down into multiple univariate series for forecasting with Time-MoE.

The next step for Time-MoE is to incorporate external factors without affecting computational efficiency and generalization, and we are currently working on this.

If you have any questions or need further assistance, please feel free to contact us.

**Comment by ketusrai** [comment]
Thank you for your reply. Looking forward to your bringing a new Time-MoE model with external factors.
